# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2acfbaa0251a096222dbeb29323dd694fe73694cc57445de1c12ade0b8a21e24fbf57ffb803da0c67ada4ca8bb9c7a8c47c89e8ec7dede35e24aa78c9fe7066a

test:
  secret_key_base: 3121ad4bf0fb2c0de0d6c881f67c037e98695e9cfe7d4f697e6d9e40c1de15ccdc854c3663f1d6233475590484fd40d8e17b658bc34a757b6968ac602f8e1ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
